import { GameTheme, TFlashCards } from '../../types';

export const Cards: {
  [k in GameTheme]: TFlashCards;
} = {
  conference: [
    'Hello, are you there?',
    "We can see you: false, but we can't hear you",
    "You're on mute!",
    'Can you unmute your microphone?',
    'Can you hear me now?',
    'Could you turn your video on?',
    'Can you see me now?',
    "Sorry: false, I didn't catch that: false, the connection is bad.",
    "You've frozen.",
    "Oh dear: false, we've lost you!",
    'Could you write that in the chat box please?',
    "I'm having trouble with my microphone.",
    'would you mind repeating that?',
    'How is everyone?',
    'Can you email that to everyone',
    'Please grant presenter rights',
    'Can we take this offline',
    'Do you see the screen',
    'Are we all on?',
    'Can everybody hear me?',
    'Did everybody get the agenda?',
    'Let’s keep this short.',
    'We’ll just wait a few minutes.',
    'Sorry I’m / we’re late.',
    'Could you speak more slowly please?',
    'I’m afraid I didn’t get that',
  ],
  'football-players': [
    'Landon Donovan',
    'Mia Hamm',
    'Abby Wambach',
    'Alfredo Di Stéfano',
    'Diego Maradona',
    'Lionel Messi',
    'José Manuel Moreno',
    'Omar Sivori',
    'Didi',
    'Artur Friedenreich',
    'Garrincha',
    'Kaká',
    'Leônidas',
    'Marta',
    'Mauro',
    'Neymar',
    'Pelé',
    'Rivaldo',
    'Romário',
    'Ronaldo',
    'Sócrates',
    'Vavá',
    'Ivor John Allchurch',
    'Viv Anderson',
    'Kenneth George Aston',
    'Alan James Ball',
  ],
  'marvel-movies': [
    'Iron Man',
    'The Incredible Hulk',
    'Iron Man 2',
    'Thor',
    'Captain America: The First Avenger',
    'Marvel’s The First Avengers',
    'Iron Man 3',
    'Thor: The Dark World',
    'Captain America: The Winter Soldier',
    'Guardians of the Galaxy',
    'Avengers: Age of Ultron',
    'Ant-Man',
    'Captain America: Civil War',
    'Doctor Strange',
    'Guardians of the Galaxy Vol. 2',
    'Spider-Man: Homecoming',
    'Thor: Ragnarok',
    'Black Panther',
    'Avengers: Infinity War',
    'Ant-Man and the Wasp',
    'Captain Marvel',
    'Avengers: Endgame',
    'Spider-Man: Far From Home',
    'Black Widow',
    'Shang-Chi and the Legend of the Ten Rings',
    'Eternals',
  ],
};
